/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication54;

import javax.swing.JFrame;

/**
 *
 * @author hyacinth mioten
 */
public class DatabaseFrame extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseFrame
     */
    public DatabaseFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignInPanel = new javax.swing.JPanel();
        Table = new javax.swing.JLabel();
        Return_Button = new javax.swing.JButton();
        Buttons = new javax.swing.JPanel();
        User_Button = new javax.swing.JButton();
        EggFryCount_Button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SignInPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        SignInPanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        SignInPanel.setLayout(null);

        Table.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Table.png"))); // NOI18N
        SignInPanel.add(Table);
        Table.setBounds(470, 20, 1460, 1040);

        Return_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Return.png"))); // NOI18N
        Return_Button.setContentAreaFilled(false);
        SignInPanel.add(Return_Button);
        Return_Button.setBounds(10, 30, 135, 49);

        Buttons.setOpaque(false);

        User_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_User.png"))); // NOI18N
        User_Button.setContentAreaFilled(false);

        EggFryCount_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Egg-Fry Count_1.png"))); // NOI18N
        EggFryCount_Button.setContentAreaFilled(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Forecast.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);

        javax.swing.GroupLayout ButtonsLayout = new javax.swing.GroupLayout(Buttons);
        Buttons.setLayout(ButtonsLayout);
        ButtonsLayout.setHorizontalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsLayout.createSequentialGroup()
                        .addComponent(EggFryCount_Button)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsLayout.createSequentialGroup()
                        .addComponent(User_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        ButtonsLayout.setVerticalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addComponent(User_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(EggFryCount_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        SignInPanel.add(Buttons);
        Buttons.setBounds(50, 390, 330, 330);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_BG.png"))); // NOI18N
        SignInPanel.add(BG);
        BG.setBounds(0, -140, 1920, 1350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 3629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel Buttons;
    private javax.swing.JButton EggFryCount_Button;
    private javax.swing.JButton Return_Button;
    private javax.swing.JPanel SignInPanel;
    private javax.swing.JLabel Table;
    private javax.swing.JButton User_Button;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
