/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication54;

import javax.swing.JFrame;

/**
 *
 * @author hyacinth mioten
 */
public class DatabaseFrame extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseFrame
     */
    public DatabaseFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatabasePanel = new javax.swing.JPanel();
        ChoicesPanel = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        ImgProcButton = new javax.swing.JButton();
        ForecastButton = new javax.swing.JButton();
        Choices2Panel = new javax.swing.JPanel();
        Separator = new javax.swing.JSeparator();
        Users = new javax.swing.JButton();
        EggFryCount = new javax.swing.JButton();
        Forecast = new javax.swing.JButton();
        DisplayField = new javax.swing.JTextField();
        DataTable = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DatabasePanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        DatabasePanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        DatabasePanel.setLayout(null);

        ChoicesPanel.setOpaque(false);

        HomeButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        ImgProcButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ImgProcButton.setText("Egg/Fry Count");
        ImgProcButton.setBorder(null);
        ImgProcButton.setBorderPainted(false);
        ImgProcButton.setContentAreaFilled(false);
        ImgProcButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ImgProcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImgProcButtonActionPerformed(evt);
            }
        });

        ForecastButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ForecastButton.setText("Forecast");
        ForecastButton.setBorder(null);
        ForecastButton.setBorderPainted(false);
        ForecastButton.setContentAreaFilled(false);
        ForecastButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout ChoicesPanelLayout = new javax.swing.GroupLayout(ChoicesPanel);
        ChoicesPanel.setLayout(ChoicesPanelLayout);
        ChoicesPanelLayout.setHorizontalGroup(
            ChoicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoicesPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(HomeButton)
                .addGap(29, 29, 29)
                .addComponent(ImgProcButton)
                .addGap(31, 31, 31)
                .addComponent(ForecastButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        ChoicesPanelLayout.setVerticalGroup(
            ChoicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChoicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImgProcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ForecastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DatabasePanel.add(ChoicesPanel);
        ChoicesPanel.setBounds(10, 10, 320, 60);

        Choices2Panel.setOpaque(false);

        Separator.setBackground(new java.awt.Color(0, 0, 0));
        Separator.setForeground(new java.awt.Color(0, 0, 0));
        Separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Separator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Users.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Users.setText("Users");
        Users.setBorder(null);
        Users.setContentAreaFilled(false);

        EggFryCount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EggFryCount.setText("Previous Egg/Fry Count");
        EggFryCount.setBorder(null);
        EggFryCount.setContentAreaFilled(false);

        Forecast.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Forecast.setText("Previous Forecast");
        Forecast.setBorder(null);
        Forecast.setContentAreaFilled(false);
        Forecast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForecastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Choices2PanelLayout = new javax.swing.GroupLayout(Choices2Panel);
        Choices2Panel.setLayout(Choices2PanelLayout);
        Choices2PanelLayout.setHorizontalGroup(
            Choices2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Choices2PanelLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(Choices2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(EggFryCount, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Forecast, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(Choices2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Choices2PanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );
        Choices2PanelLayout.setVerticalGroup(
            Choices2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Choices2PanelLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(EggFryCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Forecast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(Choices2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Choices2PanelLayout.createSequentialGroup()
                    .addContainerGap(85, Short.MAX_VALUE)
                    .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(85, Short.MAX_VALUE)))
        );

        DatabasePanel.add(Choices2Panel);
        Choices2Panel.setBounds(20, 80, 210, 530);

        DisplayField.setEditable(false);
        DisplayField.setBackground(new java.awt.Color(255, 255, 255));
        DisplayField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DisplayField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DisplayField.setText("Users' Record");
        DisplayField.setBorder(null);
        DisplayField.setOpaque(false);
        DatabasePanel.add(DisplayField);
        DisplayField.setBounds(410, 20, 160, 50);

        Table.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "First Name", "Last Name", "Contact Number", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        Table.setOpaque(false);
        Table.setPreferredSize(new java.awt.Dimension(450, 0));
        DataTable.setViewportView(Table);

        DatabasePanel.add(DataTable);
        DataTable.setBounds(410, 90, 820, 550);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/Images/I_BG.png"))); // NOI18N
        DatabasePanel.add(Background);
        Background.setBounds(-120, -10, 1580, 980);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DatabasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DatabasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        new HomeFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void ImgProcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImgProcButtonActionPerformed
        new ThesisJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ImgProcButtonActionPerformed

    private void ForecastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForecastActionPerformed
        new ForecastFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ForecastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Choices2Panel;
    private javax.swing.JPanel ChoicesPanel;
    private javax.swing.JScrollPane DataTable;
    private javax.swing.JPanel DatabasePanel;
    private javax.swing.JTextField DisplayField;
    private javax.swing.JButton EggFryCount;
    private javax.swing.JButton Forecast;
    private javax.swing.JButton ForecastButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton ImgProcButton;
    private javax.swing.JSeparator Separator;
    private javax.swing.JTable Table;
    private javax.swing.JButton Users;
    // End of variables declaration//GEN-END:variables
}
