/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication54;

import javax.swing.JFrame;

/**
 *
 * @author hyacinth mioten
 */
public class ForecastFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForecastFrame
     */
    public ForecastFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        ChoicesPanel = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        DatabaseButton = new javax.swing.JButton();
        ForecastButton = new javax.swing.JButton();
        Choices2Panel = new javax.swing.JPanel();
        Separator = new javax.swing.JSeparator();
        Users = new javax.swing.JButton();
        EggFryCount = new javax.swing.JButton();
        Forecast = new javax.swing.JButton();
        DisplayField = new javax.swing.JTextField();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        ImgDisplay = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Panel.setLayout(null);

        ChoicesPanel.setOpaque(false);

        HomeButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        DatabaseButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DatabaseButton.setText("Egg/Fry Count");
        DatabaseButton.setBorder(null);
        DatabaseButton.setBorderPainted(false);
        DatabaseButton.setContentAreaFilled(false);
        DatabaseButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseButtonActionPerformed(evt);
            }
        });

        ForecastButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ForecastButton.setText("Forecast");
        ForecastButton.setBorder(null);
        ForecastButton.setBorderPainted(false);
        ForecastButton.setContentAreaFilled(false);
        ForecastButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout ChoicesPanelLayout = new javax.swing.GroupLayout(ChoicesPanel);
        ChoicesPanel.setLayout(ChoicesPanelLayout);
        ChoicesPanelLayout.setHorizontalGroup(
            ChoicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoicesPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(HomeButton)
                .addGap(29, 29, 29)
                .addComponent(DatabaseButton)
                .addGap(31, 31, 31)
                .addComponent(ForecastButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        ChoicesPanelLayout.setVerticalGroup(
            ChoicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChoicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ForecastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.add(ChoicesPanel);
        ChoicesPanel.setBounds(10, 10, 310, 60);

        Choices2Panel.setOpaque(false);

        Separator.setBackground(new java.awt.Color(0, 0, 0));
        Separator.setForeground(new java.awt.Color(0, 0, 0));
        Separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Separator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Users.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Users.setText("Users");
        Users.setBorder(null);
        Users.setContentAreaFilled(false);
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });

        EggFryCount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EggFryCount.setText("Previous Egg/Fry Count");
        EggFryCount.setBorder(null);
        EggFryCount.setContentAreaFilled(false);

        Forecast.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Forecast.setText("Previous Forecast");
        Forecast.setBorder(null);
        Forecast.setContentAreaFilled(false);

        javax.swing.GroupLayout Choices2PanelLayout = new javax.swing.GroupLayout(Choices2Panel);
        Choices2Panel.setLayout(Choices2PanelLayout);
        Choices2PanelLayout.setHorizontalGroup(
            Choices2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Choices2PanelLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(Choices2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(EggFryCount, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Forecast, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(Choices2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Choices2PanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );
        Choices2PanelLayout.setVerticalGroup(
            Choices2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Choices2PanelLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(EggFryCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Forecast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(Choices2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Choices2PanelLayout.createSequentialGroup()
                    .addContainerGap(85, Short.MAX_VALUE)
                    .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(85, Short.MAX_VALUE)))
        );

        Panel.add(Choices2Panel);
        Choices2Panel.setBounds(20, 80, 210, 530);

        DisplayField.setEditable(false);
        DisplayField.setBackground(new java.awt.Color(255, 255, 255));
        DisplayField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DisplayField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DisplayField.setText("Forecast");
        DisplayField.setBorder(null);
        DisplayField.setOpaque(false);
        Panel.add(DisplayField);
        DisplayField.setBounds(410, 20, 100, 50);

        SearchField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        SearchField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search TestID", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N
        SearchField.setOpaque(false);
        Panel.add(SearchField);
        SearchField.setBounds(410, 80, 260, 70);

        SearchButton.setBackground(new java.awt.Color(0, 0, 0));
        SearchButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("Search");
        SearchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SearchButton.setBorderPainted(false);
        SearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel.add(SearchButton);
        SearchButton.setBounds(690, 87, 140, 60);

        ImgDisplay.setBackground(new java.awt.Color(255, 255, 255));
        ImgDisplay.setOpaque(true);
        Panel.add(ImgDisplay);
        ImgDisplay.setBounds(410, 170, 780, 500);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/Images/I_BG.png"))); // NOI18N
        Panel.add(Background);
        Background.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        new HomeFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void DatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseButtonActionPerformed
        new DatabaseFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DatabaseButtonActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        new DatabaseFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForecastFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForecastFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForecastFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForecastFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForecastFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Choices2Panel;
    private javax.swing.JPanel ChoicesPanel;
    private javax.swing.JButton DatabaseButton;
    private javax.swing.JTextField DisplayField;
    private javax.swing.JButton EggFryCount;
    private javax.swing.JButton Forecast;
    private javax.swing.JButton ForecastButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel ImgDisplay;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton Users;
    // End of variables declaration//GEN-END:variables
}
