/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication54;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author hyacinth mioten
 */
public class SignUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpFrame
     */ 
    public SignUpFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpPanel = new javax.swing.JPanel();
        SignUp_UNTextField = new javax.swing.JTextField();
        SignUp_UNLabel = new javax.swing.JLabel();
        SignUp_EmailTextField = new javax.swing.JTextField();
        SignUp_EmailLabel = new javax.swing.JLabel();
        SignUp_PassField = new javax.swing.JPasswordField();
        SignUp_PassLabel = new javax.swing.JLabel();
        SignUp_SignUButton = new javax.swing.JButton();
        SignUp_SignInOpt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SignUp_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        SignUpPanel.setLayout(null);

        SignUp_UNTextField.setBackground(new java.awt.Color(242, 244, 248));
        SignUp_UNTextField.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        SignUp_UNTextField.setForeground(new java.awt.Color(204, 204, 204));
        SignUp_UNTextField.setText("Name");
        SignUp_UNTextField.setBorder(null);
        SignUp_UNTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SignUp_UNTextField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        SignUp_UNTextField.setName(""); // NOI18N
        SignUp_UNTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SignUp_UNTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SignUp_UNTextFieldFocusLost(evt);
            }
        });
        SignUp_UNTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SignUp_UNTextFieldKeyTyped(evt);
            }
        });
        SignUpPanel.add(SignUp_UNTextField);
        SignUp_UNTextField.setBounds(190, 230, 510, 80);
        SignUp_UNTextField.getAccessibleContext().setAccessibleName("");

        SignUp_UNLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Name.png"))); // NOI18N
        SignUpPanel.add(SignUp_UNLabel);
        SignUp_UNLabel.setBounds(170, 220, 610, 120);

        SignUp_EmailTextField.setBackground(new java.awt.Color(242, 244, 248));
        SignUp_EmailTextField.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        SignUp_EmailTextField.setForeground(new java.awt.Color(204, 204, 204));
        SignUp_EmailTextField.setText("Email");
        SignUp_EmailTextField.setBorder(null);
        SignUp_EmailTextField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        SignUp_EmailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SignUp_EmailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SignUp_EmailTextFieldFocusLost(evt);
            }
        });
        SignUp_EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_EmailTextFieldActionPerformed(evt);
            }
        });
        SignUpPanel.add(SignUp_EmailTextField);
        SignUp_EmailTextField.setBounds(190, 360, 500, 80);

        SignUp_EmailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Email.png"))); // NOI18N
        SignUpPanel.add(SignUp_EmailLabel);
        SignUp_EmailLabel.setBounds(170, 350, 610, 120);

        SignUp_PassField.setBackground(new java.awt.Color(242, 244, 248));
        SignUp_PassField.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        SignUp_PassField.setForeground(new java.awt.Color(204, 204, 204));
        SignUp_PassField.setText("Password");
        SignUp_PassField.setToolTipText(" ");
        SignUp_PassField.setBorder(null);
        SignUp_PassField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        SignUp_PassField.setEchoChar('\u0000');
        SignUp_PassField.setPreferredSize(new java.awt.Dimension(70, 41));
        SignUp_PassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SignUp_PassFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SignUp_PassFieldFocusLost(evt);
            }
        });
        SignUpPanel.add(SignUp_PassField);
        SignUp_PassField.setBounds(190, 495, 490, 80);

        SignUp_PassLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Password.png"))); // NOI18N
        SignUpPanel.add(SignUp_PassLabel);
        SignUp_PassLabel.setBounds(170, 490, 610, 110);

        SignUp_SignUButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Sign Up Button.png"))); // NOI18N
        SignUp_SignUButton.setContentAreaFilled(false);
        SignUp_SignUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_SignUButtonActionPerformed(evt);
            }
        });
        SignUpPanel.add(SignUp_SignUButton);
        SignUp_SignUButton.setBounds(180, 630, 620, 140);

        SignUp_SignInOpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Sign In Option.png"))); // NOI18N
        SignUp_SignInOpt.setContentAreaFilled(false);
        SignUp_SignInOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_SignInOptActionPerformed(evt);
            }
        });
        SignUpPanel.add(SignUp_SignInOpt);
        SignUp_SignInOpt.setBounds(300, 750, 340, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Welcome.png"))); // NOI18N
        SignUpPanel.add(jLabel1);
        jLabel1.setBounds(1100, 330, 522, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Description.png"))); // NOI18N
        SignUpPanel.add(jLabel2);
        jLabel2.setBounds(970, 440, 782, 230);

        SignUp_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/I_Background.jpg"))); // NOI18N
        SignUp_BG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SignUp_BGFocusGained(evt);
            }
        });
        SignUpPanel.add(SignUp_BG);
        SignUp_BG.setBounds(0, -410, 2210, 1500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUp_SignUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_SignUButtonActionPerformed
        new ThesisJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignUp_SignUButtonActionPerformed

    private void SignUp_UNTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SignUp_UNTextFieldKeyTyped

    }//GEN-LAST:event_SignUp_UNTextFieldKeyTyped

    private void SignUp_UNTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_UNTextFieldFocusGained
        if (SignUp_UNTextField.getText().equals("Name")) {
            SignUp_UNTextField.setText("");
            SignUp_UNTextField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_SignUp_UNTextFieldFocusGained

    private void SignUp_UNTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_UNTextFieldFocusLost
        if (SignUp_UNTextField.getText().equals("")) {
            SignUp_UNTextField.setText("Name");
            SignUp_UNTextField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_SignUp_UNTextFieldFocusLost

    private void SignUp_EmailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_EmailTextFieldFocusGained
        if (SignUp_EmailTextField.getText().equals("Email")) {
            SignUp_EmailTextField.setText("");
            SignUp_EmailTextField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_SignUp_EmailTextFieldFocusGained

    private void SignUp_EmailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_EmailTextFieldFocusLost
        if (SignUp_EmailTextField.getText().equals("")) {
            SignUp_EmailTextField.setText("Email");
            SignUp_EmailTextField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_SignUp_EmailTextFieldFocusLost

    private void SignUp_PassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_PassFieldFocusGained
        if (SignUp_PassField.getText().equals("Password")) {
            SignUp_PassField.setText(null);
            SignUp_PassField.setEchoChar('*');
        }
    }//GEN-LAST:event_SignUp_PassFieldFocusGained

    private void SignUp_PassFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_PassFieldFocusLost
        if (SignUp_PassField.getText().equals("")) {
            SignUp_PassField.setText("Password");
            SignUp_PassField.setEchoChar('\u0000');
            SignUp_PassField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_SignUp_PassFieldFocusLost

    private void SignUp_BGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_BGFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_BGFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void SignUp_EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_EmailTextFieldActionPerformed

    private void SignUp_SignInOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_SignInOptActionPerformed
        new SignInFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignUp_SignInOptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JLabel SignUp_BG;
    private javax.swing.JLabel SignUp_EmailLabel;
    private javax.swing.JTextField SignUp_EmailTextField;
    private javax.swing.JPasswordField SignUp_PassField;
    private javax.swing.JLabel SignUp_PassLabel;
    private javax.swing.JButton SignUp_SignInOpt;
    private javax.swing.JButton SignUp_SignUButton;
    private javax.swing.JLabel SignUp_UNLabel;
    private javax.swing.JTextField SignUp_UNTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
