/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication54;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author hyacinth mioten
 */
public class SignUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpFrame
     */ 
    public SignUpFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        PanelBG = new RoundedPanel(50, Color.WHITE);
        FirstName = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        ContactNumber = new javax.swing.JLabel();
        ContactNumberField = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        AddressField = new javax.swing.JTextField();
        EmailAddress = new javax.swing.JLabel();
        EmailAddressField = new javax.swing.JTextField();
        CreatePassword = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JLabel();
        ConfirmPassField = new javax.swing.JPasswordField();
        PasswordCheck = new javax.swing.JCheckBox();
        SignUpButton = new javax.swing.JButton();
        DHAA = new javax.swing.JLabel();
        SignInButton = new javax.swing.JButton();
        FreshCountLabel = new javax.swing.JLabel();
        Panel_1 = new javax.swing.JPanel();
        Description = new javax.swing.JLabel();
        Description_1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        Panel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Panel.setLayout(null);

        PanelBG.setOpaque(false);

        FirstName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        FirstName.setText("First Name");

        FirstNameField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        FirstNameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        FirstNameField.setOpaque(false);

        LastName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        LastName.setText("Last Name");

        LastNameField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LastNameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        LastNameField.setOpaque(false);

        ContactNumber.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ContactNumber.setText("Contact Number");

        ContactNumberField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ContactNumberField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ContactNumberField.setOpaque(false);

        Address.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Address.setText("Address");

        AddressField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        AddressField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        AddressField.setOpaque(false);

        EmailAddress.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        EmailAddress.setText("Email Address");

        EmailAddressField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        EmailAddressField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        EmailAddressField.setOpaque(false);

        CreatePassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        CreatePassword.setText("Create Password");

        PassField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PassField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        PassField.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        PassField.setOpaque(false);

        ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ConfirmPassword.setText("Confirm Password");

        ConfirmPassField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ConfirmPassField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ConfirmPassField.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        ConfirmPassField.setOpaque(false);

        PasswordCheck.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        PasswordCheck.setText("Show Password");
        PasswordCheck.setContentAreaFilled(false);
        PasswordCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCheckActionPerformed(evt);
            }
        });

        SignUpButton.setBackground(new java.awt.Color(0, 0, 0));
        SignUpButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SignUpButton.setBorderPainted(false);
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        DHAA.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        DHAA.setText("Already have an account?");

        SignInButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        SignInButton.setForeground(new java.awt.Color(51, 153, 255));
        SignInButton.setText("Sign In");
        SignInButton.setBorder(null);
        SignInButton.setContentAreaFilled(false);
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBGLayout = new javax.swing.GroupLayout(PanelBG);
        PanelBG.setLayout(PanelBGLayout);
        PanelBGLayout.setHorizontalGroup(
            PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBGLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelBGLayout.createSequentialGroup()
                            .addComponent(EmailAddress)
                            .addGap(285, 285, 285))
                        .addGroup(PanelBGLayout.createSequentialGroup()
                            .addComponent(Address)
                            .addGap(317, 317, 317))
                        .addGroup(PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelBGLayout.createSequentialGroup()
                                .addComponent(ContactNumber)
                                .addGap(273, 273, 273))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CreatePassword)
                            .addComponent(PassField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordCheck)
                            .addComponent(SignUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConfirmPassword)
                            .addComponent(ConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ContactNumberField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EmailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelBGLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(DHAA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SignInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        PanelBGLayout.setVerticalGroup(
            PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBGLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(FirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContactNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreatePassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordCheck)
                .addGap(18, 18, 18)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DHAA)
                    .addComponent(SignInButton))
                .addGap(38, 38, 38))
        );

        Panel.add(PanelBG);
        PanelBG.setBounds(40, 20, 500, 660);

        FreshCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 75)); // NOI18N
        FreshCountLabel.setForeground(new java.awt.Color(255, 255, 255));
        FreshCountLabel.setText("WELCOME!");
        Panel.add(FreshCountLabel);
        FreshCountLabel.setBounds(710, 260, 400, 120);

        Panel_1.setOpaque(false);

        Description.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Description.setForeground(new java.awt.Color(255, 255, 255));
        Description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Description.setText("Monitor your fish growth with ease where you are a few");

        Description_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Description_1.setForeground(new java.awt.Color(255, 255, 255));
        Description_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Description_1.setText("clicks away from saving and collecting your data.");

        javax.swing.GroupLayout Panel_1Layout = new javax.swing.GroupLayout(Panel_1);
        Panel_1.setLayout(Panel_1Layout);
        Panel_1Layout.setHorizontalGroup(
            Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Description_1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
            .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        Panel_1Layout.setVerticalGroup(
            Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(Description_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        Panel.add(Panel_1);
        Panel_1.setBounds(650, 350, 520, 100);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/Images/I_Blue.jpg"))); // NOI18N
        Panel.add(Background);
        Background.setBounds(0, 0, 1920, 1280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        new HomeFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        new SignInFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignInButtonActionPerformed

    private void PasswordCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCheckActionPerformed
        if (PasswordCheck.isSelected()) {
            PassField.setEchoChar((char)0);
        } else {
            PassField.setEchoChar('*');
        }
        if (PasswordCheck.isSelected()) {
            ConfirmPassField.setEchoChar((char)0);
        } else {
            ConfirmPassField.setEchoChar('*');
        }
    }//GEN-LAST:event_PasswordCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel Background;
    private javax.swing.JPasswordField ConfirmPassField;
    private javax.swing.JLabel ConfirmPassword;
    private javax.swing.JLabel ContactNumber;
    private javax.swing.JTextField ContactNumberField;
    private javax.swing.JLabel CreatePassword;
    private javax.swing.JLabel DHAA;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Description_1;
    private javax.swing.JLabel EmailAddress;
    private javax.swing.JTextField EmailAddressField;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FreshCountLabel;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel PanelBG;
    private javax.swing.JPanel Panel_1;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JCheckBox PasswordCheck;
    private javax.swing.JButton SignInButton;
    private javax.swing.JButton SignUpButton;
    // End of variables declaration//GEN-END:variables
}

class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }