/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication54;

import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import org.opencv.core.Core;
import org.opencv.core.CvType;
import org.opencv.core.Mat;
import org.opencv.core.MatOfPoint;
import org.opencv.core.Point;
import org.opencv.core.MatOfByte;
import org.opencv.core.Scalar;
import org.opencv.core.Size;
import org.opencv.highgui.HighGui;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;


/** 
 *
 * @author hyacinth mioten
 */
public class ThesisJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String filename;
    public ThesisJFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        ImgDisplay = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        UploadButton = new javax.swing.JButton();
        RunTestButton = new javax.swing.JButton();
        SaveTestButton = new javax.swing.JButton();
        SelectLabel = new javax.swing.JLabel();
        Classification = new javax.swing.JComboBox<>();
        EggCountLabel = new javax.swing.JLabel();
        EggCountField = new javax.swing.JTextField();
        FryCountLabel = new javax.swing.JLabel();
        FryCountField = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        Panel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Panel.setLayout(null);

        ImgDisplay.setBackground(new java.awt.Color(255, 255, 255));
        ImgDisplay.setOpaque(true);
        Panel.add(ImgDisplay);
        ImgDisplay.setBounds(70, 70, 780, 500);

        Panel2.setOpaque(false);

        UploadButton.setBackground(new java.awt.Color(0, 0, 0));
        UploadButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        UploadButton.setForeground(new java.awt.Color(255, 255, 255));
        UploadButton.setText("Upload");
        UploadButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UploadButton.setBorderPainted(false);
        UploadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });

        RunTestButton.setBackground(new java.awt.Color(0, 0, 0));
        RunTestButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        RunTestButton.setForeground(new java.awt.Color(255, 255, 255));
        RunTestButton.setText("Run Test");
        RunTestButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RunTestButton.setBorderPainted(false);
        RunTestButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RunTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunTestButtonActionPerformed(evt);
            }
        });

        SaveTestButton.setBackground(new java.awt.Color(0, 0, 0));
        SaveTestButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SaveTestButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveTestButton.setText("Save Test");
        SaveTestButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SaveTestButton.setBorderPainted(false);
        SaveTestButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SaveTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveTestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(UploadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(RunTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(SaveTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UploadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RunTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        Panel.add(Panel2);
        Panel2.setBounds(70, 570, 780, 93);

        SelectLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        SelectLabel.setText("Select Image Classification:");
        Panel.add(SelectLabel);
        SelectLabel.setBounds(870, 40, 230, 40);

        Classification.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Classification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fish eggs", "Fish fries" }));
        Panel.add(Classification);
        Classification.setBounds(870, 90, 330, 60);

        EggCountLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EggCountLabel.setText("Total egg count:");
        Panel.add(EggCountLabel);
        EggCountLabel.setBounds(880, 280, 130, 30);

        EggCountField.setEditable(false);
        EggCountField.setBackground(new java.awt.Color(255, 255, 255));
        EggCountField.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        EggCountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EggCountField.setText("0000");
        EggCountField.setBorder(null);
        EggCountField.setOpaque(false);
        Panel.add(EggCountField);
        EggCountField.setBounds(880, 310, 320, 60);

        FryCountLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FryCountLabel.setText("Total fry count:");
        Panel.add(FryCountLabel);
        FryCountLabel.setBounds(880, 410, 130, 30);

        FryCountField.setEditable(false);
        FryCountField.setBackground(new java.awt.Color(255, 255, 255));
        FryCountField.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        FryCountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FryCountField.setText("0000");
        FryCountField.setBorder(null);
        FryCountField.setOpaque(false);
        Panel.add(FryCountField);
        FryCountField.setBounds(880, 440, 320, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication54/Images/I_BG.png"))); // NOI18N
        Panel.add(Background);
        Background.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(ImgDisplay.getWidth(), ImgDisplay.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        ImgDisplay.setIcon(icon);
    }//GEN-LAST:event_UploadButtonActionPerformed

    private void RunTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunTestButtonActionPerformed
        int threshold = 100;
        Random rng = new Random(12345);
        
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        Mat srcGray = new Mat();
        Mat src = Imgcodecs.imread(filename);

        Imgproc.cvtColor(src, srcGray, Imgproc.COLOR_BGR2GRAY);
        Imgproc.blur(srcGray, srcGray, new Size(3, 3));

        Mat cannyOutput = new Mat();
        Imgproc.Canny(srcGray, cannyOutput, threshold, threshold * 2);
        List<MatOfPoint> contours = new ArrayList<>();
        Mat hierarchy = new Mat();
        Imgproc.findContours(cannyOutput, contours, hierarchy, Imgproc.RETR_TREE, Imgproc.CHAIN_APPROX_SIMPLE);
        Mat drawing = Mat.zeros(cannyOutput.size(), CvType.CV_8UC3);

        int contourCount = 0;

        for (int i = 0; i < contours.size(); i++) {
            Scalar color = new Scalar(rng.nextInt(256), rng.nextInt(256), rng.nextInt(256));
            Imgproc.drawContours(drawing, contours, i, color, 1, Imgproc.LINE_8, hierarchy, 0, new Point());
            contourCount++;
        }
        System.out.println(contourCount);
        FryCountField.setText(String.valueOf(contourCount));
        ImgDisplay.setIcon(new ImageIcon(HighGui.toBufferedImage(drawing)));
    }//GEN-LAST:event_RunTestButtonActionPerformed

    private void SaveTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveTestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveTestButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThesisJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JComboBox<String> Classification;
    private javax.swing.JTextField EggCountField;
    private javax.swing.JLabel EggCountLabel;
    private javax.swing.JTextField FryCountField;
    private javax.swing.JLabel FryCountLabel;
    private javax.swing.JLabel ImgDisplay;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel Panel2;
    private javax.swing.JButton RunTestButton;
    private javax.swing.JButton SaveTestButton;
    private javax.swing.JLabel SelectLabel;
    private javax.swing.JButton UploadButton;
    // End of variables declaration//GEN-END:variables
}
